using System;
using System.Windows.Forms;
using System.Drawing;

namespace ProyectoFormularios
{
    public class FormMenu : Form
    {
        public FormMenu()
        {
            this.Text = "Menu de Ejercicios - Windows Forms";
            this.Size = new Size(430, 620);
            this.StartPosition = FormStartPosition.CenterScreen;

            Label titulo = new Label();
            titulo.Text = "Ejercicios en Windows Forms";
            titulo.Font = new Font("Segoe UI", 13F, FontStyle.Bold);
            titulo.SetBounds(20, 12, 390, 32);
            this.Controls.Add(titulo);

            FlowLayoutPanel panel = new FlowLayoutPanel();
            panel.SetBounds(15, 50, 390, 520);
            panel.AutoScroll = true;
            panel.FlowDirection = FlowDirection.TopDown;
            panel.WrapContents = false;
            this.Controls.Add(panel);

            Button b01 = new Button();
            b01.Text = "Ejercicio 1 - Salario con horas extra";
            b01.Width = 360; b01.Height = 30;
            b01.Click += (s, e) => new FormEj01().Show();
            panel.Controls.Add(b01);
            Button b02 = new Button();
            b02.Text = "Ejercicio 2 - Descuento por sueldo";
            b02.Width = 360; b02.Height = 30;
            b02.Click += (s, e) => new FormEj02().Show();
            panel.Controls.Add(b02);
            Button b03 = new Button();
            b03.Text = "Ejercicio 3 - Descuento por monto";
            b03.Width = 360; b03.Height = 30;
            b03.Click += (s, e) => new FormEj03().Show();
            panel.Controls.Add(b03);
            Button b04 = new Button();
            b04.Text = "Ejercicio 4 - Segundos a minuto";
            b04.Width = 360; b04.Height = 30;
            b04.Click += (s, e) => new FormEj04().Show();
            panel.Controls.Add(b04);
            Button b05 = new Button();
            b05.Text = "Ejercicio 5 - Minutos a dias/horas/min";
            b05.Width = 360; b05.Height = 30;
            b05.Click += (s, e) => new FormEj05().Show();
            panel.Controls.Add(b05);
            Button b06 = new Button();
            b06.Text = "Ejercicio 6 - Suma de N naturales";
            b06.Width = 360; b06.Height = 30;
            b06.Click += (s, e) => new FormEj06().Show();
            panel.Controls.Add(b06);
            Button b07 = new Button();
            b07.Text = "Ejercicio 7 - Suma de salarios";
            b07.Width = 360; b07.Height = 30;
            b07.Click += (s, e) => new FormEj07().Show();
            panel.Controls.Add(b07);
            Button b08 = new Button();
            b08.Text = "Ejercicio 8 - Salario horas x tarifa";
            b08.Width = 360; b08.Height = 30;
            b08.Click += (s, e) => new FormEj08().Show();
            panel.Controls.Add(b08);
            Button b09 = new Button();
            b09.Text = "Ejercicio 9 - Analisis de N notas";
            b09.Width = 360; b09.Height = 30;
            b09.Click += (s, e) => new FormEj09().Show();
            panel.Controls.Add(b09);
            Button b10 = new Button();
            b10.Text = "Ejercicio 10 - Suma de digitos";
            b10.Width = 360; b10.Height = 30;
            b10.Click += (s, e) => new FormEj10().Show();
            panel.Controls.Add(b10);
            Button b11 = new Button();
            b11.Text = "Ejercicio 11 - Factura con IVA";
            b11.Width = 360; b11.Height = 30;
            b11.Click += (s, e) => new FormEj11().Show();
            panel.Controls.Add(b11);
            Button b12 = new Button();
            b12.Text = "Ejercicio 12 - Contar pares/impares/pos/neg";
            b12.Width = 360; b12.Height = 30;
            b12.Click += (s, e) => new FormEj12().Show();
            panel.Controls.Add(b12);
            Button b13 = new Button();
            b13.Text = "Ejercicio 13 - Factorial";
            b13.Width = 360; b13.Height = 30;
            b13.Click += (s, e) => new FormEj13().Show();
            panel.Controls.Add(b13);
            Button b14 = new Button();
            b14.Text = "Ejercicio 14 - Media de numeros";
            b14.Width = 360; b14.Height = 30;
            b14.Click += (s, e) => new FormEj14().Show();
            panel.Controls.Add(b14);
            Button b15 = new Button();
            b15.Text = "Ejercicio 15 - Suma y producto pares 20-400";
            b15.Width = 360; b15.Height = 30;
            b15.Click += (s, e) => new FormEj15().Show();
            panel.Controls.Add(b15);
            Button b18 = new Button();
            b18.Text = "Ejercicio 18 - Primera vocal";
            b18.Width = 360; b18.Height = 30;
            b18.Click += (s, e) => new FormEj18().Show();
            panel.Controls.Add(b18);
            Button b19 = new Button();
            b19.Text = "Ejercicio 19 - Parte fraccionaria";
            b19.Width = 360; b19.Height = 30;
            b19.Click += (s, e) => new FormEj19().Show();
            panel.Controls.Add(b19);
            Button b20 = new Button();
            b20.Text = "Ejercicio 20 - Ecuacion cuadratica";
            b20.Width = 360; b20.Height = 30;
            b20.Click += (s, e) => new FormEj20().Show();
            panel.Controls.Add(b20);
            Button b21 = new Button();
            b21.Text = "Ejercicio 21 - Operaciones con 2 numeros";
            b21.Width = 360; b21.Height = 30;
            b21.Click += (s, e) => new FormEj21().Show();
            panel.Controls.Add(b21);
            Button b22 = new Button();
            b22.Text = "Ejercicio 22 - Cubo y raiz cuadrada";
            b22.Width = 360; b22.Height = 30;
            b22.Click += (s, e) => new FormEj22().Show();
            panel.Controls.Add(b22);
            Button b23 = new Button();
            b23.Text = "Ejercicio 23 - Operaciones con 2 numeros";
            b23.Width = 360; b23.Height = 30;
            b23.Click += (s, e) => new FormEj23().Show();
            panel.Controls.Add(b23);
            Button b24 = new Button();
            b24.Text = "Ejercicio 24 - Area de triangulo";
            b24.Width = 360; b24.Height = 30;
            b24.Click += (s, e) => new FormEj24().Show();
            panel.Controls.Add(b24);
            Button b25 = new Button();
            b25.Text = "Ejercicio 25 - Hipotenusa";
            b25.Width = 360; b25.Height = 30;
            b25.Click += (s, e) => new FormEj25().Show();
            panel.Controls.Add(b25);
            Button b26 = new Button();
            b26.Text = "Ejercicio 26 - Circunferencia, area y volumen";
            b26.Width = 360; b26.Height = 30;
            b26.Click += (s, e) => new FormEj26().Show();
            panel.Controls.Add(b26);
            Button b27 = new Button();
            b27.Text = "Ejercicio 27 - Total consumos restaurant";
            b27.Width = 360; b27.Height = 30;
            b27.Click += (s, e) => new FormEj27().Show();
            panel.Controls.Add(b27);
            Button b28 = new Button();
            b28.Text = "Ejercicio 28 - Suma desde 8 hasta N";
            b28.Width = 360; b28.Height = 30;
            b28.Click += (s, e) => new FormEj28().Show();
            panel.Controls.Add(b28);
            Button b29 = new Button();
            b29.Text = "Ejercicio 29 - Egresos en caja";
            b29.Width = 360; b29.Height = 30;
            b29.Click += (s, e) => new FormEj29().Show();
            panel.Controls.Add(b29);
            Button b30 = new Button();
            b30.Text = "Ejercicio 30 - Promedio de 2 notas";
            b30.Width = 360; b30.Height = 30;
            b30.Click += (s, e) => new FormEj30().Show();
            panel.Controls.Add(b30);
            Button b31 = new Button();
            b31.Text = "Ejercicio 31 - Clasificar por deporte";
            b31.Width = 360; b31.Height = 30;
            b31.Click += (s, e) => new FormEj31().Show();
            panel.Controls.Add(b31);
            Button b32 = new Button();
            b32.Text = "Ejercicio 32 - Claves de la fiesta";
            b32.Width = 360; b32.Height = 30;
            b32.Click += (s, e) => new FormEj32().Show();
            panel.Controls.Add(b32);
        }
    }
}
